### ISSUE TITLE
The One Probe catched error

### ISSUE THREAD

**Issue by IAmNotGEM** [GregTechCEu/GregTech#1270]
### GregTech CEu Version

gregtech-1.12.2-2.4.4-beta

### Environment

Catserver

### New Worlds

No

### Cross-Mod Interaction

Unsure

### Expected Behavior

.

### Actual Behavior

[Server thread/DEBUG] [theoneprobe]: The One Probe catched error: 
java.lang.NoSuchMethodError: net.minecraft.util.StringUtils.func_76337_a(I)Ljava/lang/String;
	at gregtech.integration.theoneprobe.provider.FuelableInfoProvider.addProbeInfo(FuelableInfoProvider.java:57) ~[FuelableInfoProvider.class:?]
	at gregtech.integration.theoneprobe.provider.FuelableInfoProvider.addProbeInfo(FuelableInfoProvider.java:20) ~[FuelableInfoProvider.class:?]
	at gregtech.integration.theoneprobe.provider.CapabilityInfoProvider.addProbeInfo(CapabilityInfoProvider.java:33) ~[CapabilityInfoProvider.class:?]
	at mcjty.theoneprobe.network.PacketGetInfo.getProbeInfo(PacketGetInfo.java:144) ~[PacketGetInfo.class:?]
	at mcjty.theoneprobe.network.PacketGetInfo.access$600(PacketGetInfo.java:34) ~[PacketGetInfo.class:?]
	at mcjty.theoneprobe.network.PacketGetInfo$Handler.handle(PacketGetInfo.java:109) ~[PacketGetInfo$Handler.class:?]
	at mcjty.theoneprobe.network.PacketGetInfo$Handler.lambda$onMessage$0(PacketGetInfo.java:102) ~[PacketGetInfo$Handler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:910) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:475) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:834) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

### Steps to Reproduce

.

**Comment by LAGIdiot** [comment]
Can you please provide more context to this. On what block were you looking when this happened?
