### ISSUE TITLE
gregtech.client.model.modelfactories.ActiveVariantBlockBakedModel.getQuads

### ISSUE THREAD

**Issue by IAmNotGEM** [GregTechCEu/GregTech#1272]
### GregTech CEu Version

gregtech-1.12.2-2.4.4-beta

### Environment

Catserver

### Side Crashed

Client

### New Worlds

No

### Steps to Reproduce

.

### Crash Report

java.lang.NullPointerException
    at gregtech.client.model.modelfactories.ActiveVariantBlockBakedModel.getQuads(ActiveVariantBlockBakedModel.java:47)
    at net.minecraft.client.renderer.BlockModelRenderer.renderModelBrightnessColor(BlockModelRenderer.java:466)
    at net.minecraft.client.renderer.BlockModelRenderer.renderModelBrightness(BlockModelRenderer.java:492)
    at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlockBrightness(BlockRendererDispatcher.java:120)
    at codechicken.lib.render.block.CCBlockRendererDispatcher.renderBlockBrightness(CCBlockRendererDispatcher.java:131)
    at com.elytradev.architecture.client.render.CustomBlockDispatcher.renderBlockBrightness(CustomBlockDispatcher.java:72)
    at com.direwolf20.buildinggadgets.common.tools.ToolRenders.lambda$renderBuilderOverlay$1(ToolRenders.java:124)
    at com.direwolf20.buildinggadgets.common.tools.ToolRenders$$Lambda$4946.00000000C914EF00.accept(Unknown Source)
    at java.util.ArrayList.forEach(ArrayList.java:1257)
    at com.direwolf20.buildinggadgets.common.tools.ToolRenders.renderBuilderOverlay(ToolRenders.java:115)
    at com.direwolf20.buildinggadgets.client.proxy.ClientProxy.renderWorldLastEvent(ClientProxy.java:92)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_330_ClientProxy_renderWorldLastEvent_RenderWorldLastEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:196)
    at sun.reflect.GeneratedMethodAccessor90.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.optifine.reflect.Reflector.callVoid(Reflector.java:669)
    at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1959)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1621)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1390)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:4614)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by LAGIdiot** [comment]
Can you please provide more context to this. Especially when this error occurred. Did you placed new block down or looked at something specific?
