### ISSUE TITLE
BUG: version 2.5.2 breaks the GT Comunity pack Greenhouse

### ISSUE THREAD

**Issue by firendlyGhost** [GregTechCEu/GregTech#1506]
### GregTech CEu Version

2.5.2

### Modpack Used

GT Comunity pack

### Addons Installed

Gregicality MB

### Environment

Multiplayer ONLY

### New Worlds

Unsure

### Cross-Mod Interaction

No

### Expected Behavior

Updated to the new version 2.5.2, form 2.5.0.
Im playing on the modpack so the only thing i changed was the GT mod java.
Didnt expect the greenhouse to break, it happens in 1 of 2 ways.

### Actual Behavior

1-Server only:

Scenario 1: Log onto server, get a small error about the greenshouse but, greenhouse controller is placed in world, works just fine ![greenhouse bug1](https://user-images.githubusercontent.com/53128966/218558308-7ed55148-d76b-4799-a7d3-6f6a57277506.PNG)

Scneraio 2: (happens if i reload the server from scratch) Get big ass error in ingame chat

[19:30:23] [Server thread/ERROR] [GregTech]: Failed to load MetaTileEntity with invalid ID multiblocktweaker:greenhouse
[19:30:25] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 2761ms behind, skipping 55 tick(s)
[19:30:31] [Netty Server IO #1/INFO] [STDOUT]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:49]: [littletiles] Patched net.minecraft.network.NettyCompressionDecoder ...
[19:30:31] [Netty Server IO #1/INFO] [FML]: Client protocol version 2
[19:30:31] [Netty Server IO #1/INFO] [FML]: Client attempting to join with 113 mods : tombmanygraves@1.12-4.1.0,p455w0rdslib@2.3.161,netherportalfix@5.3.17,creativecoredummy@1.0.0,incontrol@3.9.18,modnametooltip@1.10.1,findme@1.0.0,ctm@MC1.12.2-1.0.2.31,betterquesting@4.1.0,controlling@3.0.10,xaeroworldmap@1.28.0,placebo@1.6.0,forgelin@1.8.3,microblockcbe@2.6.2.83,stg@1.12.2-1.2.3,randompatches@1.12.2-1.22.1.10,buildinggadgets@2.8.4,projectred-illumination@4.9.4.120,wct@3.12.97,betterbuilderswands@0.13.2,ftblib@5.4.7.2,xporbclump@1.1,architecturecraft@@VERSION@,tombmanygraves2api@1.12.2-1.0.0,tipthescales@1.0.4,torchmaster@1.8.5.0,crafttweakerjei@2.0.3,openglider@@VERSION@,mtlib@3.0.7,chatcalculator@@VERSION@,moresoundconfig@1.0.4,modtweaker@4.0.19,resourceloader@1.5.3,spark@1.5.2,littletilescore@1.0.0,projectred-core@4.9.4.120,lunatriuscore@1.2.0.42,topaddons@1.12.2-1.13.0,projectred-transmission@4.9.4.120,elevatorid@1.3.14,FML@8.0.99.99,projectred-integration@4.9.4.120,tombmanypluginscosmeticarmorreworked@1.0.0,aiimprovements@0.0.1.1,moreoverlays@1.15.1,forgemultipartcbe@2.6.2.83,overpoweredarmorbar@@VERSION@,topextras@1.0.1,badwithernocookiereloaded@1.12.2-3.4.18,codechickenlib@3.2.3.358,fastleafdecay@v14,betteradvancements@0.1.0.77,unloader@1.2.0,clienttweaks@3.1.11,ctgui@1.0.0,ae2wtlib@1.0.34,mixinbooter@7.0,customskinloader@14.9,jei@4.24.2,attributefix@1.0.10,loliasm@5.6,xtones@1.2.2,mcp@9.42,diethopper@1.1,appliedenergistics2@rv6-stable-7-extended_life-v0.54.20,naturescompass@1.8.5,framedcompactdrawers@1.2.7,chameleon@1.12-4.1.3,surge@2.0.79,inventorytweaks@1.64+dev.151.822d839,foamfixcore@7.7.4,toastcontrol@1.8.1,crafttweaker@4.1.20,enderstorage@2.4.6.137,forge@14.23.5.2859,xaeroworldmap_core@1.12.2-1.0,gregtech@2.5.2-beta,phosphor-lighting@1.12.2-0.2.7,ftbutilities@5.4.1.131,chesttransporter@2.8.8,ironchest@1.12.2-7.0.67.844,craftingtweaks@9.0.1,minecraft@1.12.2,gcym@1.1.6,enchdesc@1.1.20,theoneprobe@1.4.28,mousetweaks@3.1.2,betterbedrockgen@6.0.2,baubles@1.5.2,creativecore@1.10.0,ding@1.0.2,jeiintegration@1.6.0,xaerominimap@22.15.1,ftbbackups@1.1.0.1,fastbench@1.7.4,oauth@1.06.4,storagedrawers@5.2.2,harvest@1.12-1.2.8-25,mrtjpcore@2.1.4.43,moresoundconfigcore@1.0.0,fastfurnace@1.3.1,appleskin@1.0.14,ingameinfoxml@2.8.2.94,chisel@MC1.12.2-1.0.2.45,minecraftmultipartcbe@2.6.2.83,xaerominimap_core@1.12.2-1.0,foamfix@@VERSION@,randomtweaks@1.12.2-2.8.3.1,dynamistics@1.0.2,multiblocktweaker@1.12.2-stable-gtceu-1.8.2,backpack@3.0.2,cosmeticarmorreworked@1.12.2-v5a,littletiles@1.5.0
[19:30:31] [Netty Server IO #1/INFO] [CodeChickenLib-ConfigSync]: Skipping config sync, No mods have registered a syncable config.
[19:30:32] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[19:30:32] [Server thread/INFO] [minecraft/PlayerList]: GamerGabriPt[/192.168.1.69:56054] logged in with entity id 116 at (289.58204822784876, 68.0, -616.001022495473)
[19:30:32] [Server thread/INFO] [minecraft/DedicatedServer]: GamerGabriPt joined the game
[19:30:32] [Server thread/INFO] [buildinggadgets]: Sending SyncedConfig to freshly logged in player GamerGabriPt.
[19:30:32] [Server thread/ERROR] [FML]: FMLIndexedMessageCodec exception caught
io.netty.handler.codec.EncoderException: java.lang.RuntimeException: Undefined discriminator for message type com.github.lunatrius.ingameinfo.network.message.MessageSeed in channel ingameinfoxml
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250) [SimpleNetworkWrapper.class:?]
        at com.github.lunatrius.ingameinfo.handler.PlayerHandler.onPlayerLogin(PlayerHandler.java:15) [PlayerHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_465_PlayerHandler_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:575) [FMLCommonHandler.class:?]
        at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:219) [pl.class:?]
        at shadows.fastbench.net.HijackedDedicatedPlayerList.initializeConnectionToPlayer(HijackedDedicatedPlayerList.java:19) [HijackedDedicatedPlayerList.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255) [NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) [NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:205) [NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285) [gw.class:?]
        at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.RuntimeException: Undefined discriminator for message type com.github.lunatrius.ingameinfo.network.message.MessageSeed in channel ingameinfoxml
        at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:76) ~[FMLIndexedMessageToMessageCodec.class:?]
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[minecraft_server.1.12.2.jar:?]
        ... 26 more

### Steps to Reproduce

1- change only the GT file for the mod
2- Log onto server
3- exit server and reboot
4- Greenhouse gone+ Big script conflict

**Comment by firendlyGhost** [comment]
Aditional: Forgot to mention that it REMOVES the greenhouse controller from the world, its still in JEI and it has a crafting recipe but is UNCRAFTABLE with that recipe

**Comment by Jdimango** [comment]
I'm playing Nomifactory 1.5.1 which updated CEU to 2.5.2 and I'm having the same issue except with the Microminers.

> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblock_dml.zs:81 > a method available but �4none�r matches the parameters (ZenTypeNative: crafttweaker.block.IBlockState)\nThis is �ousually�r an error in your script, not in the mod\nwithBaseTexture(�rZenTypeNative: null.null)
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblock_dml.zs:138 > any values not yet supported
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblock_dml.zs:138 > not a valid lvalue
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblock_dml.zs:139 > any values not yet supported
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblock_dml.zs:139 > not a valid lvalue
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblock_dml.zs:158 > any values not yet supported
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblock_dml.zs:158 > any values not yet supported
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblock_dml.zs:158 > any values not yet supported
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblock_dml.zs:158 > any values not yet supported
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblock_dml.zs:158 > any values not yet supported
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblock_dml.zs:158 > any values not yet supported
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblock_dml.zs:158 > any values not yet supported
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblock_dml.zs:158 > any values not yet supported
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: [crafttweaker]: Error executing {[0:crafttweaker]: multiblock_dml.zs}: null, caused by java.lang.NullPointerException
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:24 > a method available but �4none�r matches the parameters (ZenTypeNative: crafttweaker.block.IBlockState)\nThis is �ousually�r an error in your script, not in the mod\nwithBaseTexture(�rZenTypeNative: null.null)
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:49 > any values not yet supported
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:49 > not a valid lvalue
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:50 > any values not yet supported
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:50 > not a valid lvalue
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:54 > a method available but �4none�r matches the parameters (ZenTypeNative: crafttweaker.block.IBlockState)\nThis is �ousually�r an error in your script, not in the mod\nwithBaseTexture(�rZenTypeNative: null.null)
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:106 > any values not yet supported
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:106 > not a valid lvalue
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:107 > any values not yet supported
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:107 > not a valid lvalue
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:111 > a method available but �4none�r matches the parameters (ZenTypeNative: crafttweaker.block.IBlockState)\nThis is �ousually�r an error in your script, not in the mod\nwithBaseTexture(�rZenTypeNative: null.null)
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:204 > any values not yet supported
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:204 > not a valid lvalue
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:205 > any values not yet supported
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:205 > not a valid lvalue
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:209 > a method available but �4none�r matches the parameters (ZenTypeNative: crafttweaker.block.IBlockState)\nThis is �ousually�r an error in your script, not in the mod\nwithBaseTexture(�rZenTypeNative: null.null)
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:230 > any values not yet supported
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:230 > not a valid lvalue
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:231 > any values not yet supported
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:231 > not a valid lvalue
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:237 > a method available but �4none�r matches the parameters (ZenTypeNative: crafttweaker.block.IBlockState)\nThis is �ousually�r an error in your script, not in the mod\nwithBaseTexture(�rZenTypeNative: null.null)
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:282 > any values not yet supported
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:282 > not a valid lvalue
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:283 > any values not yet supported
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:283 > not a valid lvalue
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:286 > any values not yet supported
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:286 > not a valid lvalue
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:293 > a method available but �4none�r matches the parameters (ZenTypeNative: crafttweaker.block.IBlockState)\nThis is �ousually�r an error in your script, not in the mod\nwithBaseTexture(�rZenTypeNative: null.null)
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:342 > any values not yet supported
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:342 > not a valid lvalue
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:343 > any values not yet supported
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:343 > not a valid lvalue
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:346 > any values not yet supported
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:346 > not a valid lvalue
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:402 > any values not yet supported
> ...
> Truncated log because it was just repeated
> ...
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:841 > any values not yet supported
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:841 > any values not yet supported
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:841 > any values not yet supported
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:841 > any values not yet supported
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:841 > any values not yet supported
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: multiblocks_normal.zs:841 > any values not yet supported
> [21:28:10] [Client thread/INFO]: [CHAT] �cERROR: [crafttweaker]: Error executing {[0:crafttweaker]: multiblocks_normal.zs}: null, caused by java.lang.NullPointerException
>

**Comment by ALongStringOfNumbers** [comment]
This should be fixed with #1544
