### ISSUE TITLE
Multiblock Tanks broken in v2.8.0

### ISSUE THREAD

**Issue by tmtvl** [GregTechCEu/GregTech#2219]
### GregTech CEu Version

v2.8.0

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

When right-clicking on a multiblock tank controller I expect the UI to show; I also expect the tank to automatically output fluids from a valve rotated downward.

### Actual Behavior

When right-clicking on a multiblock tank controller the UI doesn't show; the tank also doesn't output fluids (and presumably also doesn't accept fluids).

### Steps to Reproduce

Build a multiblock tank and right-click on the controller.

### Additional Information

When right-clicking on the controller block I get the following error in the log:

`java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 0
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_392]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_392]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_392]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at gregtech.api.capability.impl.FluidTankList.getTankAt(FluidTankList.java:66) ~[FluidTankList.class:?]
	at gregtech.common.metatileentities.multi.MetaTileEntityMultiblockTank.createUITemplate(MetaTileEntityMultiblockTank.java:132) ~[MetaTileEntityMultiblockTank.class:?]
	at gregtech.api.metatileentity.multiblock.MultiblockWithDisplayBase.createUI(MultiblockWithDisplayBase.java:552) ~[MultiblockWithDisplayBase.class:?]
	at gregtech.api.metatileentity.MetaTileEntityUIFactory.createUITemplate(MetaTileEntityUIFactory.java:30) ~[MetaTileEntityUIFactory.class:?]
	at gregtech.api.metatileentity.MetaTileEntityUIFactory.createUITemplate(MetaTileEntityUIFactory.java:18) ~[MetaTileEntityUIFactory.class:?]
	at gregtech.api.gui.UIFactory.openUI(UIFactory.java:38) ~[UIFactory.class:?]
	at gregtech.api.metatileentity.MetaTileEntity.onRightClick(MetaTileEntity.java:438) ~[MetaTileEntity.class:?]
	at gregtech.api.metatileentity.multiblock.MultiblockControllerBase.onRightClick(MultiblockControllerBase.java:498) ~[MultiblockControllerBase.class:?]
	at gregtech.common.metatileentities.multi.MetaTileEntityMultiblockTank.onRightClick(MetaTileEntityMultiblockTank.java:125) ~[MetaTileEntityMultiblockTank.class:?]
	at gregtech.api.block.machines.BlockMachine.func_180639_a(BlockMachine.java:359) ~[BlockMachine.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:449) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_392]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_392]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more`

**Comment by tmtvl** [comment]
As an additional note, I tried this on a clean install of Minecraft 1.12.2 with the latest Forge (14.23.5.2860) with only GregTech (2.8.0-beta) and CodeChicken Lib (3.2.3.358) installed.
