### ISSUE TITLE
[BUG] Incompability w. Tough As Nails

### ISSUE THREAD

**Issue by Shazuli** [GregTechCEu/GregTech#465]
**Describe the bug**
GTCEu appears to be incompatible with [Tough As Nails](https://www.curseforge.com/minecraft/mc-mods/tough-as-nails) mod and crashes on startup.

**Versions**
Forge: 14.23.5.2860
GTCE: 2.0.2-beta
TAN: 3.1.0

<details>
  <summary>crash-2022-01-04_19.48.17-client.txt</summary>

```
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 2022-01-04 19:48:17 CET
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tough As Nails (toughasnails)
Caused by: java.lang.NullPointerException
    at toughasnails.init.ModConfig.lambda$init$1(ModConfig.java:75)
    at toughasnails.init.ModConfig.populateDataMap(ModConfig.java:92)
    at toughasnails.init.ModConfig.init(ModConfig.java:75)
    at toughasnails.core.ToughAsNails.init(ToughAsNails.java:83)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Linux (amd64) version 5.4.0-91-generic
  Java Version: 1.8.0_291, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 5120545200 bytes (4883 MB) / 8051490816 bytes (7678 MB) up to 8051490816 bytes (7678 MB)
  JVM Flags: 2 total; -Xms4096m -Xmx8064m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 LoliASM 4.4 Powered by Forge 14.23.5.2860 127 mods loaded, 126 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                           | Version            | Source                                              | Signature                                |
       |:----- |:---------------------------- |:------------------ |:--------------------------------------------------- |:---------------------------------------- |
       | LCHI  | minecraft                    | 1.12.2             | minecraft.jar                                       | None                                     |
       | LCHI  | mcp                          | 9.42               | minecraft.jar                                       | None                                     |
       | LCHI  | FML                          | 8.0.99.99          | forge-1.12.2-14.23.5.2860-universal.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHI  | forge                        | 14.23.5.2860       | forge-1.12.2-14.23.5.2860-universal.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHI  | creativecoredummy            | 1.0.0              | minecraft.jar                                       | None                                     |
       | LCHI  | entity_culling               | 2.0.5              | minecraft.jar                                       | None                                     |
       | LCHI  | itemphysic                   | 1.4.0              | minecraft.jar                                       | None                                     |
       | LCHI  | smoothfontcore               | mc1.12.2-2.1.2     | minecraft.jar                                       | None                                     |
       | LCHI  | opencomputers|core           | 1.7.5.192          | minecraft.jar                                       | None                                     |
       | LCHI  | smoothfont                   | mc1.12.2-2.1.2     | SmoothFont-mc1.12.2-2.1.2.jar                       | None                                     |
       | LCHI  | libvulpes                    | 0.4.2.-84          | LibVulpes-1.12.2-0.4.2-84-universal.jar             | None                                     |
       | LCHI  | advancedrocketry             | 2.0.0.-255         | AdvancedRocketry-1.12.2-2.0.0-255-universal.jar     | None                                     |
       | LCHI  | aiimprovements               | 0.0.1.1            | AIImprovements-1.12.1-0.0.1b1.jar                   | None                                     |
       | LCHI  | akashictome                  | 1.2-12             | AkashicTome-1.2-12.jar                              | None                                     |
       | LCHI  | ctm                          | MC1.12.2-1.0.2.31  | CTM-MC1.12.2-1.0.2.31.jar                           | None                                     |
       | LCHI  | appliedenergistics2          | rv6-stable-7       | appliedenergistics2-rv6-stable-7.jar                | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
       | LCHI  | armorpointspp                | v2.0.0-rc1         | armorpointspp-1.12.2-2.0.1.jar                      | None                                     |
       | LCHI  | carrots                      | 1.0.0b1            | carrotslib-mc1.12.2-1.0.0b1.jar                     | None                                     |
       | LCHI  | armorunder                   | 1.0.0              | armorunder-mc1.12.2-1.0.0.jar                       | None                                     |
       | LCHI  | crafttweaker                 | 4.1.20             | CraftTweaker2-1.12-4.1.20.658.jar                   | None                                     |
       | LCHI  | mtlib                        | 3.0.7              | MTLib-3.0.7.jar                                     | None                                     |
       | LCHI  | modtweaker                   | 4.0.19             | modtweaker-4.0.20.4.jar                             | None                                     |
       | LCHI  | jei                          | 4.16.1.301         | jei_1.12.2-4.16.1.301.jar                           | None                                     |
       | LCHI  | quark                        | r1.6-179           | Quark-r1.6-179.jar                                  | None                                     |
       | LCHI  | autoreglib                   | 1.3-32             | AutoRegLib-1.3-32.jar                               | None                                     |
       | LCHI  | baubles                      | 1.5.2              | Baubles-1.12-1.5.2.jar                              | None                                     |
       | LCHI  | bettermineshafts             | 1.12.2-2.2.1       | BetterMineshaftsForge-1.12.2-2.2.1.jar              | None                                     |
       | LCHI  | betternether                 | 0.1.8.6            | betternether-0.1.8.6.jar                            | None                                     |
       | LCHI  | thaumcraft                   | 6.1.BETA26         | Thaumcraft-1.12.2-6.1.BETA26.jar                    | None                                     |
       | LCHI  | botania                      | r1.10-364          | Botania+r1.10-364.4.jar                             | None                                     |
       | LCHI  | consecration                 | 1.0.6              | consecration-1.12.2-1.0.6.jar                       | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCHI  | patchouli                    | 1.0-20             | Patchouli-1.0-20.jar                                | None                                     |
       | LCHE  | toughasnails                 | 3.1.0.139          | ToughAsNails-1.12.2-3.1.0.139-universal.jar         | None                                     |
       | LCH   | bewitchment                  | 0.22.63            | bewitchment-1.12.2-0.0.22.64.jar                    | None                                     |
       | LCH   | bibliocraft                  | 2.4.5              | BiblioCraft[v2.4.5][MC1.12.2].jar                   | None                                     |
       | LCH   | bloodmoon                    | 1.5.3              | Bloodmoon-MC1.12.2-1.5.3.jar                        | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCH   | blur                         | 1.0.4-14           | Blur-1.0.4-14.jar                                   | None                                     |
       | LCH   | bookshelf                    | 2.3.577            | Bookshelf-1.12.2-2.3.577.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | chameleon                    | 1.12-4.1.3         | Chameleon-1.12-4.1.3.jar                            | None                                     |
       | LCH   | chunkanimator                | 1.2                | ChunkAnimator-MC1.12-1.2.jar                        | None                                     |
       | LCH   | codechickenlib               | 3.2.3.357          | CodeChickenLib-1.12.2-3.2.3.357-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | asielib                      | 1.0.0              | Computronics-1.12.2-1.6.6.jar                       | None                                     |
       | LCH   | endercore                    | 1.12.2-0.5.76      | EnderCore-1.12.2-0.5.76.jar                         | None                                     |
       | LCH   | enderio                      | 5.3.70             | EnderIO-base-1.12.2-5.3.70.jar                      | None                                     |
       | LCH   | forestry                     | 5.8.2.387          | forestry_1.12.2-5.8.2.387.jar                       | None                                     |
       | LCH   | gregtech                     | 2.0.2-beta         | gregtech-1.12.2-2.0.2-beta.jar                      | None                                     |
       | LCH   | opencomputers                | 1.7.5.192          | OpenComputers-MC1.12.2-1.7.5.192.jar                | None                                     |
       | LCH   | tis3d                        | 1.5.1.37           | TIS-3D-MC1.12.2-1.5.1.37.jar                        | None                                     |
       | LCH   | computronics                 | 1.6.6              | Computronics-1.12.2-1.6.6.jar                       | None                                     |
       | LCH   | ctgui                        | 1.0.0              | CraftTweaker2-1.12-4.1.20.658.jar                   | None                                     |
       | LCH   | crafttweakerjei              | 2.0.3              | CraftTweaker2-1.12-4.1.20.658.jar                   | None                                     |
       | LCH   | creativecore                 | 1.10.0             | CreativeCore_v1.10.61_mc1.12.2.jar                  | None                                     |
       | LCH   | cyberware                    | 0.2.11.29          | cyberware-1.12.2-0.2.11.29.jar                      | None                                     |
       | LCH   | damagetilt                   | 0.1.0              | DamageTilt-1.12.2-0.1.0.jar                         | None                                     |
       | LCH   | eleccore                     | 1.9.452            | ElecCore-1.12.2-1.9.452.jar                         | None                                     |
       | LCH   | mcjtylib_ng                  | 3.5.0              | mcjtylib-1.12-3.5.0.jar                             | None                                     |
       | LCH   | deepresonance                | 1.8.0              | deepresonance-1.12-1.8.0.jar                        | None                                     |
       | LCH   | diethopper                   | 1.1                | diethopper-1.1.jar                                  | None                                     |
       | LCH   | sereneseasons                | 1.2.18             | SereneSeasons-1.12.2-1.2.18-universal.jar           | None                                     |
       | LCH   | orelib                       | 3.6.0.1            | OreLib-1.12.2-3.6.0.1.jar                           | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCH   | dsurround                    | 3.6.2.1            | DynamicSurroundings-1.12.2-3.6.2.1.jar              | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCH   | enderiobase                  | 5.3.70             | EnderIO-base-1.12.2-5.3.70.jar                      | None                                     |
       | LCH   | enderioconduits              | 5.3.70             | EnderIO-conduits-1.12.2-5.3.70.jar                  | None                                     |
       | LCH   | enderiopowertools            | 5.3.70             | EnderIO-conduits-1.12.2-5.3.70.jar                  | None                                     |
       | LCH   | enderioconduitsopencomputers | 5.3.70             | EnderIO-conduits-opencomputers-1.12.2-5.3.70.jar    | None                                     |
       | LCH   | enderiointegrationforestry   | 5.3.70             | EnderIO-integration-forestry-1.12.2-5.3.70.jar      | None                                     |
       | LCH   | enderiomachines              | 5.3.70             | EnderIO-machines-1.12.2-5.3.70.jar                  | None                                     |
       | LCH   | fluidlogged_api              | 1.6.2              | Fluidlogged-API-v1.6.2-mc1.12.2.jar                 | None                                     |
       | LCH   | forgemultipartcbe            | 2.6.2.83           | ForgeMultipart-1.12.2-2.6.2.83-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | microblockcbe                | 2.6.2.83           | ForgeMultipart-1.12.2-2.6.2.83-universal.jar        | None                                     |
       | LCH   | minecraftmultipartcbe        | 2.6.2.83           | ForgeMultipart-1.12.2-2.6.2.83-universal.jar        | None                                     |
       | LCH   | cfm                          | 6.3.1              | furniture-6.3.1-1.12.2.jar                          | None                                     |
       | LCH   | gtce2oc                      | 1.8.0              | gtce2oc-1.12.2-1.8.0.jar                            | None                                     |
       | LCH   | gbook                        | 2.9.5              | Guidebook-1.12.2-2.9.5.jar                          | None                                     |
       | LCH   | hardcoredarkness             | 2.0                | HardcoreDarkness-MC1.12.2-2.0.jar                   | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCH   | ichunutil                    | 7.2.2              | iChunUtil-1.12.2-7.2.2.jar                          | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCH   | itemscroller                 | 0.12.0             | itemscroller-1.12.2-0.12.0.jar                      | 2b03e1423915a189b8094816baa18f239d576dff |
       | LCH   | jeibees                      | 0.9.0.5            | jeibees-0.9.0.5-mc1.12.2.jar                        | None                                     |
       | LCH   | journeymap                   | 1.12.2-5.7.0       | journeymap-1.12.2-5.7.0.jar                         | None                                     |
       | LCH   | mixinbooter                  | 2.0                | mixinbooter-2.0.jar                                 | None                                     |
       | LCH   | loliasm                      | 4.4                | loliasm-4.4.jar                                     | None                                     |
       | LCH   | loottweaker                  | 0.3.0              | LootTweaker-0.3.0+MC1.12.2.jar                      | None                                     |
       | LCH   | mobdismemberment             | 7.0.0              | MobDismemberment-1.12.2-7.0.0.jar                   | None                                     |
       | LCH   | mrtjpcore                    | 2.1.4.43           | MrTJPCore-1.12.2-2.1.4.43-universal.jar             | None                                     |
       | LCH   | namepain                     | 1.4.0              | namepain-1.4.0+forge-1.12.x.jar                     | None                                     |
       | LCH   | netherportalfix              | 5.3.13             | NetherPortalFix_1.12.1-5.3.13.jar                   | None                                     |
       | LCH   | ca.chead.oc-wasm             | 1.12.2-0.2.0       | oc-wasm-1.12-0.2.0.jar                              | None                                     |
       | LCH   | ocrocketry                   | 1.1.0-beta         | OCRocketry-1.1.1-beta.jar                           | None                                     |
       | LCH   | particleculling              | 1.0                | particleculling-1.12.2-v1.0.1.jar                   | None                                     |
       | LCH   | peacefulsurface              | 1.12.2-v1b         | PeacefulSurface-1.12.2-v1b.jar                      | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCH   | performant                   | 1.12.2-1.4         | performant-1.12.2-1.10.jar                          | None                                     |
       | LCH   | pneumaticcraft               | 1.12.2-0.11.15-398 | pneumaticcraft-repressurized-1.12.2-0.11.15-398.jar | None                                     |
       | LCH   | projectred-core              | 4.9.4.120          | ProjectRed-1.12.2-4.9.4.120-Base.jar                | None                                     |
       | LCH   | projectred-integration       | 4.9.4.120          | ProjectRed-1.12.2-4.9.4.120-integration.jar         | None                                     |
       | LCH   | projectred-transmission      | 4.9.4.120          | ProjectRed-1.12.2-4.9.4.120-integration.jar         | None                                     |
       | LCH   | projectred-illumination      | 4.9.4.120          | ProjectRed-1.12.2-4.9.4.120-lighting.jar            | None                                     |
       | LCH   | quarkoddities                | 1                  | QuarkOddities-1.12.2.jar                            | None                                     |
       | LCH   | redstoneflux                 | 2.1.0              | RedstoneFlux-1.12-2.1.0.6-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCH   | additionalstructures         | 2.3.1              | Rex's-Additional-Structures-1.12.x-(v.2.3.1).jar    | None                                     |
       | LCH   | rockhounding_core            | 3.27               | rockhounding_core-1.12.2-3.27.jar                   | None                                     |
       | LCH   | rockhounding_chemistry       | 1.12.2-3.61        | rockhounding_chemistry-1.12.2-3.61.jar              | None                                     |
       | LCH   | rsgauges                     | 1.2.4              | rsgauges-1.12.2-1.2.4.jar                           | ed58ed655893ced6280650866985abcae2bf7559 |
       | LCH   | savemystronghold             | 1.12.2-1.0.0       | savemystronghold-1.12.2-1.0.0.jar                   | None                                     |
       | LCH   | serenetweaks                 | 0.0.1              | SereneTweaks-1.0.jar                                | None                                     |
       | LCH   | sgcraft                      | 2.0.3              | SGCraft-2.0.5.jar                                   | None                                     |
       | LCH   | smoothwater                  | 0.1.4              | SmoothWater-0.1.4.jar                               | None                                     |
       | LCH   | soundfilters                 | 0.12.1_for_1.12    | SoundFilters-0.12.1_for_1.12.jar                    | None                                     |
       | LCH   | storagedrawers               | 1.12.2-5.4.0       | StorageDrawers-1.12.2-5.4.0.jar                     | None                                     |
       | LCH   | tandimensions                | 0.3.0              | tandimensions-0.3.0.jar                             | None                                     |
       | LCH   | tcresearchpatcher            | 1.12.2-1.1.2       | ThaumcraftResearchPatcher-1.12.2-1.1.2.jar          | 8f678591ba6f78d579e553a8aa94b4c4766cb13d |
       | LCH   | thaumicaugmentation          | 1.12.2-2.1.4       | ThaumicAugmentation-1.12.2-2.1.4.jar                | 8f678591ba6f78d579e553a8aa94b4c4766cb13d |
       | LCH   | thaumicjei                   | 1.6.0              | ThaumicJEI-1.12.2-1.6.0-27.jar                      | None                                     |
       | LCH   | thaumicenergistics           | 2.2.3              | thaumicenergistics-2.2.4.jar                        | None                                     |
       | LCH   | thaumicspeedup               | 2.0                | thaumicspeedup-2.0.jar                              | None                                     |
       | LCH   | tips                         | 1.0.9              | Tips-1.12.2-1.0.9.jar                               | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | travelersbackpack            | 1.0.35             | TravelersBackpack-1.12.2-1.0.35.jar                 | None                                     |
       | LCH   | tbintegration                | 1.0.1              | TravelersBackpackIntegration-1.12.2-1.0.1.jar       | None                                     |
       | LCH   | traverse                     | 1.6.0              | Traverse-1.12.2-1.6.0-69.jar                        | None                                     |
       | LCH   | vanillafix                   | 1.0.10-150         | VanillaFix-1.0.10-150.jar                           | None                                     |
       | LCH   | worldstripper                | 1.6.0-1.12.2       | World-Stripper-1.6.0-1.12.2.jar                     | None                                     |
       | LCH   | phosphor-lighting            | 1.12.2-0.2.6       | phosphor-1.12.2-0.2.6+build50-universal.jar         | f0387d288626cc2d937daa504e74af570c52a2f1 |
       | LCH   | commons0815                  | 1.4.0              | Commons0815-1.12.2-1.4.0.jar                        | None                                     |
       | LCH   | guitoolkit                   | 1.4.0              | Commons0815-1.12.2-1.4.0.jar                        | None                                     |
       | LCH   | rendertoolkit                | 1.4.0              | Commons0815-1.12.2-1.4.0.jar                        | None                                     |
       | LCH   | openglasses                  | @VERSION@-53       | OpenGlasses-MC1.12.2-2.2-53.jar                     | None                                     |
       | LCH   | eleccoreloader               | 1.9.452            | ElecCore-1.12.2-1.9.452.jar                         | None                                     |
       | UD    | advancedrocketrycore         | 1                  | minecraft.jar                                       | None                                     |
  Loaded coremods (and transformers): CreativePatchingLoader (CreativeCore_v1.10.61_mc1.12.2.jar)
                                        
                                      CorePlugin (SmoothFont-mc1.12.2-2.1.2.jar)
                                        bre.smoothfont.asm.Transformer
                                      TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
                                        li.cil.oc.common.asm.ClassTransformer
                                      MixinBooter (mixinbooter-2.0.jar)
                                        
                                      Thaumcraft Research Patcher Core Plugin (ThaumcraftResearchPatcher-1.12.2-1.1.2.jar)
                                        thecodex6824.tcresearchpatcher.Transformer
                                      BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.22.64.jar)
                                        
                                      TransformLoader (DynamicSurroundings-1.12.2-3.6.2.1.jar)
                                        
                                      Quark Plugin (Quark-r1.6-179.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      PerformantLoadingPlugin (performant-1.12.2-1.10.jar)
                                        
                                      LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
                                        lumien.bloodmoon.asm.ClassTransformer
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      BlurPlugin (Blur-1.0.4-14.jar)
                                        com.tterrag.blur.BlurTransformer
                                      ItemPatchingLoader (ItemPhysic_Full_1.4.34_mc1.12.2.jar)
                                        com.creativemd.itemphysic.ItemTransformer
                                      LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
                                        lumien.hardcoredarkness.asm.ClassTransformer
                                      SmoothWaterCore (SmoothWater-0.1.4.jar)
                                        pl.asie.smoothwater.SmoothWaterTransformer
                                      Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-2.1.4.jar)
                                        thecodex6824.thaumicaugmentation.core.TATransformer
                                      GregTechLoadingPlugin (gregtech-1.12.2-2.0.2-beta.jar)
                                        gregtech.core.GregTechTransformer
                                      LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
                                        lumien.chunkanimator.asm.ClassTransformer
                                      SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      Fluidlogged Plugin (Fluidlogged-API-v1.6.2-mc1.12.2.jar)
                                        git.jbredwards.fluidlogged_api.asm.swapper.ASMSwapper
                                        git.jbredwards.fluidlogged_api.asm.ASMHandler$Transformer
                                      LoliASM (loliasm-4.4.jar)
                                        
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      ParticleCullingLoadingPlugin (particleculling-1.12.2-v1.0.1.jar)
                                        
                                      AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-2.0.0-255-universal.jar)
                                        zmaster587.advancedRocketry.asm.ClassTransformer
                                      EntityCullingPlugin (EntityCulling-1.12.2-2.0.5.jar)
                                        meldexun.entityculling.plugin.ClassTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 460.91.03' Renderer: 'GeForce GTX 660/PCIe/SSE2'
  AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
  Ender IO: No known problems detected.
            Authlib is : /home/simon/.local/share/multimc/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
            
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !!!You are looking at the diagnostics information, not at the crash.       !!!
            !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  Suspected Mods: Tough As Nails (toughasnails)
  Launched Version: MultiMC5
  LWJGL: 2.9.4
  OpenGL: GeForce GTX 660/PCIe/SSE2 GL version 4.6.0 NVIDIA 460.91.03, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 12x Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
```

**Comment by htmlcsjs** [comment]
are you sure that removing CEu fixes it?

**Comment by Shazuli** [comment]
Alright, think I figured out why it wasn't working. Apparently TAN crashes the game if you specify an invalid block or item in TAN's configuration file for temperature or drink stat. I had totally missed that GTCEu removed Purple Drink.

**Comment by htmlcsjs** [comment]
we did?

**Comment by htmlcsjs** [comment]
we didnt, just that the drink probally has a different id now

**Comment by Shazuli** [comment]
Tried searching for it in JEI and got nothing. It's still called that right?

**Comment by htmlcsjs** [comment]
i think so https://github.com/GregTechCEu/GregTech/blob/f46594da743a5b54d708c4dc1b38671b2c3a77d0/src/main/java/gregtech/common/items/MetaItems.java#L431

**Comment by Shazuli** [comment]
Huh... maybe I missed it. Don't really want to start my PC again just to check that.
