### ISSUE TITLE
Crash with Construct's Armory mod.

### ISSUE THREAD

**Issue by magcicada** [GregTechCEu/GregTech#615]
When open the Armor Forge of Construct's Armory, the game will crash because of the player render.

Here is the crash report:
java.lang.NullPointerException: Rendering entity in world
	at gregtech.client.event.ClientEventHandler.onPlayerRender(ClientEventHandler.java:76)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_93_ClientEventHandler_onPlayerRender_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:59)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:28)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.gui.inventory.GuiInventory.func_147046_a(SourceFile:128)
	at c4.conarm.client.gui.GuiPreviewPanel.func_146976_a(GuiPreviewPanel.java:53)
	at slimeknights.mantle.client.gui.GuiModule.handleDrawGuiContainerBackgroundLayer(GuiModule.java:102)
	at slimeknights.mantle.client.gui.GuiMultiModule.func_146976_a(GuiMultiModule.java:95)
	at c4.conarm.client.gui.GuiArmorStation.func_146976_a(GuiArmorStation.java:565)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at slimeknights.mantle.client.gui.GuiMultiModule.func_73863_a(GuiMultiModule.java:174)
	at c4.conarm.client.gui.GuiArmorStation.func_73863_a(GuiArmorStation.java:200)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by htmlcsjs** [comment]
can conferm it happens, here is the full log:
[crash-2022-02-04_11.28.23-client.txt](https://github.com/GregTechCEu/GregTech/files/8002605/crash-2022-02-04_11.28.23-client.txt)
